steps:
  - name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      - -ceu
      - |
        tags=(-t "${_IMAGE_REPOSITORY}:sha-${_COMMIT_SHA}")
        if [[ -n "${_FLOATING_TAG}" ]]; then
          tags+=(-t "${_FLOATING_TAG}")
        fi

        docker build -f "${_DOCKERFILE}" "${tags[@]}" "${_BUILD_CONTEXT}"
        docker push "${_IMAGE_REPOSITORY}:sha-${_COMMIT_SHA}"

        if [[ -n "${_FLOATING_TAG}" ]]; then
          docker push "${_FLOATING_TAG}"
        fi

options:
  dynamicSubstitutions: true
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _BUILD_CONTEXT: .
  _DOCKERFILE: containers/app/Dockerfile
  _IMAGE_REPOSITORY: europe-west6-docker.pkg.dev/example-project/foehncast-docker/foehncast-app
  _COMMIT_SHA: dev
  _FLOATING_TAG: ""
