services:
  development_env:
    container_name: development_env
    build: .
    working_dir: /workspace
    depends_on:
      - objectstore
      - model-registry
    environment:
      - FSSPEC_S3_KEY=${OBJECTSTORE_ACCESS_KEY}
      - FSSPEC_S3_SECRET=${OBJECTSTORE_SECRET_KEY}
      - FSSPEC_S3_ENDPOINT_URL=${OBJECTSTORE_ENDPOINT}
      # Use the Compose service name inside the Docker network.
      - MLFLOW_TRACKING_URI=http://model-registry:5001
      - GIT_PYTHON_REFRESH=quiet
    volumes:
      - ../../:/workspace
    networks:
      - development
      - production
